### ISSUE TITLE
This mod is broken with new terrain system.

### ISSUE THREAD

**Issue by biouxtai** [NNaso/ValheimMods#1]
The new terrain system in Valheim breaks the Speedy Paths mod to where my character was constantly running but moving slower than encumbered with no control over direction. Mouse movement turned camera, but character didn't change direction or move faster. Another player on my server mentioned that this mod caused them to be permanently stuck in sneak mode, but unable to move at all. Once we disabled this mod, everything worked as expected.

**Comment by AlexandruVerenca** [comment]
Similar issue on my end, was stuck sliding endlessly over terrain in sneak mode, the weird part of it was that i was invincible. /killme command didn't do anything except reduce my health to 1 and i somehow managed to slide into water and there was no stamina decrease. Disabling the mod fixed it.

**Comment by jsza** [comment]
AFAICT, Valheim `0.150.3` update renamed `Heightmap.m_clearedMask` to `m_paintMask`. Should be a matter of changing this line: https://github.com/NNaso/ValheimMods/blob/main/SpeedyPaths/SpeedyPaths.cs#L288

**Comment by MrDecepticon** [comment]
Same experience here. Character as soon as they touched the ground it did not allow me to stop running, couldn't change direction and if I logged out and back in while on any terrain  I just sort of slid around in place.

**Comment by NNaso** [comment]
Excellent, thank you very much guys!

Update rolled out while i was sleeping.

Thanks @jsza, ill merge in your pull request and push up some new binaries after testing.
