### ISSUE TITLE
Very poor optimiatization reported

### ISSUE THREAD

**Issue by lupuleasa-core** [NNaso/ValheimMods#6]
Some people on reddit noticed this

https://www.reddit.com/r/ModdedValheim/comments/syx40s/comment/hy3zf4b/?utm_source=share&utm_medium=web2x&context=3

Can this mod be made to only update the path status more rarely?

Right now it is increasing CPU use by a lot

**Comment by NNaso** [comment]
This is most likely the query to the terrain mod color for the path type. I haven't profiled this in a while, but maybe recently something changed, this can def be costly though, it probably would not hurt to rate limit the entire path check less frequently.

**Comment by lupuleasa-core** [comment]
Yeah, rarer polling (every 3 seconds even) would be GREAT to have, as some modpacks use a lot of mods, and each one adds up

if from 50 mods from this modpack for example, Pathfinder and Speedy Paths stand out, then there is something out of line

https://valheim.thunderstore.io/package/Loopuleasa/Vanilla_Expanded/

**Comment by NNaso** [comment]
Hey dudes, sorry for the delay.
I've been super busy and don't play Valheim much anymore, so it's taken me a while to get to this.

I've refactored the ground check to be much more efficient, 
- Ground Check will now early break out if the player is on a constructed object.
- Ground Check has changed from multiple GetPixel calls to a single GetPixels call on the paint map.
- There is a new tuneable value "Ground Sensor Interval", this is interval between ground checks. By default it is 1 second. Between intervals it will use the last detected ground type for modifier calculations.

I don't see any noticeable difference in CPU useage / performance between having the mod running / uninstalled. But take this with a grain of salt, as I'm running very few mods on a system with a 5900x.
